### ISSUE TITLE
"Usecols do not match columns..." error

### ISSUE THREAD

**Issue by akey7** [NREL/celavi#103]
When I execute the `develop` branch of CELAVI, I get the following error message with the stack trace below. In particular, note `ValueError: Usecols do not match columns, columns expected but not found: ['vmt_max', 'in_state_only']`

Is this an input data issue?

```
loading routing graph
Traceback (most recent call last):
  File "/Users/akey/Projects/celavi/celavi/celavi/__main__.py", line 259, in <module>
    routes_computed = Router.get_all_routes(
  File "/Users/akey/Projects/celavi/celavi/celavi/routing.py", line 136, in get_all_routes
    route_pairs = Data.RoutePairs(fpath=route_pair_file,backfill=backfill)
  File "/Users/akey/Projects/celavi/celavi/celavi/data_manager.py", line 271, in __init__
    super(RoutePairs,self).__init__(df=df, fpath=fpath, columns=columns,
  File "/Users/akey/Projects/celavi/celavi/celavi/data_manager.py", line 28, in __init__
    _df = pd.DataFrame({}) if df is None and fpath is None else self.load(fpath=fpath,
  File "/Users/akey/Projects/celavi/celavi/celavi/data_manager.py", line 75, in load
    raise e
  File "/Users/akey/Projects/celavi/celavi/celavi/data_manager.py", line 64, in load
    _df = pd.read_csv(filepath_or_buffer=fpath, sep=',', dtype=columns,
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 135, in __init__
    self._validate_usecols_names(usecols, self.orig_names)
  File "/Users/akey/anaconda3/envs/celavi/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 866, in _validate_usecols_names
    raise ValueError(
ValueError: Usecols do not match columns, columns expected but not found: ['vmt_max', 'in_state_only']
```

**Comment by rjhanes** [comment]
I believe PRs 48-51 in the data repo should resolve this. It was an update to route_pairs that made it to the code branch but not the active data branches. My bad!

**Comment by akey7** [comment]
Thank @rjhanes ! It works now, closing issue!
